// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.order_service.proto;

public interface GetAllProductsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order_service.GetAllProductsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .order_service.CreateProductResponse products = 1;</code>
   */
  java.util.List<com.example.order_service.proto.CreateProductResponse> 
      getProductsList();
  /**
   * <code>repeated .order_service.CreateProductResponse products = 1;</code>
   */
  com.example.order_service.proto.CreateProductResponse getProducts(int index);
  /**
   * <code>repeated .order_service.CreateProductResponse products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .order_service.CreateProductResponse products = 1;</code>
   */
  java.util.List<? extends com.example.order_service.proto.CreateProductResponseOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .order_service.CreateProductResponse products = 1;</code>
   */
  com.example.order_service.proto.CreateProductResponseOrBuilder getProductsOrBuilder(
      int index);
}
