// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.order_service.proto;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_service_CreateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_service_CreateProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_service_CreateProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_service_CreateProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_service_GetAllProductsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_service_GetAllProductsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_service_ProductIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_service_ProductIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_service_UpdateProductQuantityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_service_UpdateProductQuantityRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\rorder_service\032\033google/pro" +
      "tobuf/empty.proto\"Z\n\024CreateProductReques" +
      "t\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\r\n\005" +
      "price\030\003 \001(\001\022\020\n\010quantity\030\004 \001(\005\"g\n\025CreateP" +
      "roductResponse\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t" +
      "\022\023\n\013description\030\003 \001(\t\022\r\n\005price\030\004 \001(\001\022\020\n\010" +
      "quantity\030\005 \001(\005\"P\n\026GetAllProductsResponse" +
      "\0226\n\010products\030\001 \003(\0132$.order_service.Creat" +
      "eProductResponse\"\036\n\020ProductIdRequest\022\n\n\002" +
      "id\030\001 \001(\005\"<\n\034UpdateProductQuantityRequest" +
      "\022\n\n\002id\030\001 \001(\005\022\020\n\010quantity\030\002 \001(\0052\270\004\n\016Produ" +
      "ctService\022\\\n\rCreateProduct\022#.order_servi" +
      "ce.CreateProductRequest\032$.order_service." +
      "CreateProductResponse\"\000\022Q\n\016GetAllProduct" +
      "s\022\026.google.protobuf.Empty\032%.order_servic" +
      "e.GetAllProductsResponse\"\000\022U\n\nGetProduct" +
      "\022\037.order_service.ProductIdRequest\032$.orde" +
      "r_service.CreateProductResponse\"\000\022S\n\rDel" +
      "eteProduct\022\037.order_service.ProductIdRequ" +
      "est\032\037.order_service.ProductIdRequest\"\000\022b" +
      "\n\013AddProducts\022+.order_service.UpdateProd" +
      "uctQuantityRequest\032$.order_service.Creat" +
      "eProductResponse\"\000\022e\n\016RemoveProducts\022+.o" +
      "rder_service.UpdateProductQuantityReques" +
      "t\032$.order_service.CreateProductResponse\"" +
      "\000B#\n\037com.example.order_service.protoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_order_service_CreateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_service_CreateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_service_CreateProductRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "Price", "Quantity", });
    internal_static_order_service_CreateProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_order_service_CreateProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_service_CreateProductResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Price", "Quantity", });
    internal_static_order_service_GetAllProductsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_order_service_GetAllProductsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_service_GetAllProductsResponse_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_order_service_ProductIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_order_service_ProductIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_service_ProductIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_order_service_UpdateProductQuantityRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_order_service_UpdateProductQuantityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_service_UpdateProductQuantityRequest_descriptor,
        new java.lang.String[] { "Id", "Quantity", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
