// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.order_service.proto;

public interface ProductIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order_service.ProductIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
