// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.order_service.proto;

public interface UpdateProductQuantityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order_service.UpdateProductQuantityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();
}
